// Generated by LiveScript 1.2.0
var buildTaiwan, buildData, convert, idx, updateValue, main;
buildTaiwan = function(cb){
  return d3.json('twTown1982.topo.json', function(data){
    var topo, topomesh, color, ref$, w, h, m, prj, path, svg;
    topo = topojson.feature(data, data.objects["twTown1982.geo"]);
    topomesh = topojson.mesh(data, data.objects["twTown1982.geo"], function(a, b){
      return a !== b;
    });
    color = d3.scale.category20();
    ref$ = [400, 600], w = ref$[0], h = ref$[1];
    m = [20, 20, 20, 20];
    prj = d3.geo.mercator().center([120.979531, 23.978567]).scale(100000);
    path = d3.geo.path().projection(prj);
    svg = d3.select('body').append('svg').attr('width', w).attr('height', h).attr('viewBox', "0 0 800 600").attr('preserveAspectRatio', 'xMidYMid');
    svg.selectAll('path.county').data(topo.features).enter().append('path').attr('class', 'county').attr('d', path).style('fill', function(){
      return color(Math.random());
    }).style('stroke', 'none').style('opacity', 0.9);
    svg.append('path').attr('class', 'boundary').datum(topomesh).attr('d', path).style('fill', 'none').style('stroke', "rgba(0,0,0,0.5)").style('stroke-width', '1px');
    return cb(svg, topo);
  });
};
buildData = function(cb){
  return d3.json('total.json', function(it){
    return cb(it);
  });
};
convert = function(county, town){
  if (county === '台北市' || county === '台北縣' || county === '台中縣' || county === '台南縣' || county === '高雄縣') {
    town = town.substring(0, town.length - 1) + "區";
    if (county === '台北縣') {
      county = '新北市';
    }
    county = county.replace('縣', '市');
  }
  return [county, town];
};
idx = 93;
updateValue = function(svg, topo, data){
  var ref$, min, max, i$, len$, it, ref1$, county, town, color, frange;
  ref$ = [-1, -1], min = ref$[0], max = ref$[1];
  for (i$ = 0, len$ = (ref$ = topo.features).length; i$ < len$; ++i$) {
    it = ref$[i$];
    ref1$ = convert(it.properties.COUNTYNAME, it.properties.TOWNNAME), county = ref1$[0], town = ref1$[1];
    it.properties.value = data.value[idx][1][county][town];
    if (min === -1 || min > it.properties.value) {
      min = it.properties.value;
    }
    if (max === -1 || max < it.properties.value) {
      max = it.properties.value;
    }
  }
  color = d3.scale.linear().domain([min, max]).range(['#000', '#f00']);
  frange = d3.scale.linear().domain([min, max]).range([254, 255]);
  return svg.selectAll('path.county').style('fill', function(it){
    return "rgba(" + it.properties.value + ",0,0,1)";
  });
};
main = function($scope, $interval){
  return buildData(function(data){
    return buildTaiwan(function(svg, topo){
      return $interval(function(){
        $scope.idx = idx;
        updateValue(svg, topo, data);
        idx = idx + 1;
        if (idx > 101) {
          return idx = 93;
        }
      }, 1000);
    });
  });
};